language: node_js
node_js: stable

sudo: false

#cache
cache:
  directories:
    - "node_modules"


notifications:
  email:
    recipients:
      - daniel_wangt@163.com
    on_success: never
    on_failure: always

# S: Build Lifecycle
install:
  - npm install
 # - gem install travis
 # - travis login --pro --github-token ${GH_TOKEN}

before_script:
  - export TZ='Asia/Shanghai'
  - npm install -g gulp
  - npm install --save-dev gulp
  - npm install --save-dev gulp-less
  - npm install --save-dev gulp-rename
  - npm install --save-dev gulp-minify-css
  - npm install --save-dev gulp-autoprefixer
  - npm install --save-dev gulp-uglify
  - npm install --save-dev jshint gulp-jshint
  - npm install --save-dev jshint-stylish
  - npm install --save-dev gulp-notify
  - npm install --save-dev gulp-plumber
  - npm install --save-dev gulp-htmlclean
  - npm install --save-dev gulp-htmlmin
  - npm install --save-dev gulp-rev-append
  - npm install --save-dev gulp-sequence
  - npm install --save-dev gulp-watch
  - npm install --save-dev require-dir
  - chmod +x _travis.sh

script:
  - hexo clean && hexo g
  - gulp

after_success:
 # - LAST_BUILD_NUMBER=68
 # - for i in $(seq 1 $LAST_BUILD_NUMBER ); do  travis logs $i --delete --force ; done

deploy:
  skip_cleanup: true
  keep-history: true

after_script:
  - ./_travis.sh

# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/MrDanielWT/mrdanielwt.github.io.git
